name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  tests:
    runs-on: ${{matrix.os}}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ matrix.node-version }}-pnpm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ matrix.node-version }}-pnpm-

      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 7

      - run: docker-compose up -d

      - name: Wait for Postgres to be healthy
        run: |
          until docker-compose exec -T postgres pg_isready; do
            echo "Waiting for Postgres to be healthy"
            sleep 2
          done

      - run: pnpm install
      - run: pnpm test

      - name: Shutdown Docker
        run: docker-compose down
        if: always()
